### PR TITLE
Add Gradle 4.10.3 to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
https://github.com/travis-ci/travis-ci/issues/10290

**Comment by gliptak** [comment]
@szpak would you be OK with switching to OpenJDK?

**Comment by szpak** [comment]
@gliptak Definitely it is a very good idea. However, I'm no longer involved in that project, nor have rights to merge anything in.

@4finance Is this project still alive?

**Comment by gliptak** [comment]
This one is maintained https://github.com/ben-manes/gradle-versions-plugin

https://github.com/functionaljava/functionaljava/pull/395

**Pull request closed without merging**
