### PR TITLE
[#25] Fixed dependency version comparison

### PR DESCRIPTION
**Pull request by cbuleandra**
Hi guys,

While investigating the bug, I've stumbled upon an existing implementation from Maven and decided to use it instead of our custom Version implementation, http://maven.apache.org/ref/3.3.1/maven-artifact/xref/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html. This seems to resolve the bug.

What do you think?

### CODE REVIEW

**Comment by szpak** [comment]
+1

**Comment by marcingrzejszczak** [comment]
Cool +1 !!

**Comment by marcingrzejszczak** [comment]
I love it when people delete plenty of my unnecessary code :D How on earth didn't I find that class? :P

**Comment by marcingrzejszczak** [comment]
@szpak maybe let @cbuleandra  merge this and then let's release 1.3.1 and after that let's merge this https://github.com/4finance/uptodate-gradle-plugin/pull/26 ?

**Comment by cbuleandra** [comment]
Merged, you can proceed with releasing 1.3.1.

**Comment by szpak** [comment]
That's fine for me. We would need to get some new features for 2.0.0 :).

**Pull request merged**
